# Generated by Django 2.0 on 2018-01-07 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecweb', '0011_auto_20180103_0243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='testgrade',
            name='student',
        ),
        migrations.RemoveField(
            model_name='testgrade',
            name='test_event',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='TestGrade',
        ),
    ]
